language: python
branches:
  only:
    - master
python:
  - "3.6"      # current default Python on Travis CI
install:
  - pip install -r requirements.txt
script:
  #- skip       # Travis requires a `script` property, but we do not need it
  - python -m unittest
  - python setup.py build_sphinx
jobs:
  include:
    - stage: build and test # This stage builds and lints in parallel
      name: Build
