language: python
branches:
  only:
    - master
python:
  - "3.6"      # current default Python on Travis CI
install:
  - pip install -r requirements.txt
script:
  - skip       # Travis requires a `script` property, but we do not need it
jobs:
  include:
    - skip
